export const data = [
    {
        id: 1,
        nombre: "Lemuel",
        edad: 24,
        genero: false,
        peso: 87,
        modulos: 3,
    },
    {
        id: 2,
        nombre: "Annetta",
        edad: 37,
        genero: true,
        peso: 4,
        modulos: 1,
    },
    {
        id: 3,
        nombre: "Allison",
        edad: 41,
        genero: false,
        peso: 17,
        modulos: 4,
    },
    {
        id: 4,
        nombre: "Vallie",
        edad: 2,
        genero: true,
        peso: 69,
        modulos: 5,
    },
    {
        id: 5,
        nombre: "Keshaun",
        edad: 5,
        genero: true,
        peso: 9,
        modulos: 3,
    },
    {
        id: 6,
        nombre: "Jarrett",
        edad: 23,
        genero: false,
        peso: 39,
        modulos: 8,
    },
]